"""'v2.0'

Revision ID: 699dac3bdd6
Revises: 6821722f2a1
Create Date: 2016-11-01 22:02:23.107000

"""

# revision identifiers, used by Alembic.
revision = '699dac3bdd6'
down_revision = '6821722f2a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
